receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 1000
    timeout: 10s

exporters:
  clickhousemetricsexporter:
    dsn: tcp://clickhouse:9000
  clickhousetracesexporter:
    dsn: tcp://clickhouse:9000

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousetracesexporter]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhousemetricsexporter]