apiVersion: batch/v1
kind: Job
metadata:
  name: arteci-api-seeder
spec:
  template:
    spec:
      containers:
      - name: seeder
        image: othnielparfait/arteci-api:latest # Utilise votre image Docker Hub
        command: ["python", "api/src/seed_data.py"]
        env:
        - name: MINIO_URL
          value: "http://minio:9000" # Adresse interne du réseau Kubernetes
        - name: ACCESS_KEY
          value: "minioadmin"
        - name: SECRET_KEY
          value: "minioadminpassword"
      restartPolicy: Never
